### ISSUE TITLE
The audit log links are hardcoded to /cp

### ISSUE THREAD

**Issue by sebszocinski** [serieseight/statamic-audit-log#6]
Links break if you have changed the default `/cp` path for the control panel. 

In my case i'm using `/admin`.

It should detect this somehow?

**Comment by aryehraber** [comment]
Hey @sebszocinski! (Long time!)

Nice catch on this one! You're right, this shouldn't be hardcoded -- will try and get a fix in asap.

**Comment by sebszocinski** [comment]
hey @aryehraber! what a nice surprise! no worries at all, nothing urgent.

**Comment by aryehraber** [comment]
@sebszocinski This should be fixed now, feel free to reopen if you continue having issues!
